# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_owner', models.IntegerField(verbose_name='Owner')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
                ('image', models.ImageField(upload_to='post/', verbose_name='Image')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Create')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('moder', models.BooleanField(default=False, verbose_name='Moder')),
            ],
            options={
                'verbose_name': 'Post',
                'ordering': ['create'],
                'verbose_name_plural': 'Posts',
                'db_table': 'post',
            },
        ),
    ]
