# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20171128_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='moder',
        ),
        migrations.RemoveField(
            model_name='post',
            name='moder',
        ),
    ]
